<?
## Email File -> notify a buyer when a seller has created a new cart invoice for him
## called from shopping_cart.php and members_area.php

if ( !defined('INCLUDED') ) { die("Access Denied"); }

$row_details = $db->get_sql_row("SELECT u.username, u.email, sc.sc_id FROM " . DB_PREFIX . "shopping_carts sc 
	LEFT JOIN " . DB_PREFIX . "users u on u.user_id=sc.buyer_id WHERE 
	sc.sc_id='" . $mail_input_id . "'");
$send = true; ## always send

## text message - editable
$text_message = 'Dear %1$s,
	
A new invoice has been generated by a seller for a set of items you have purchased from him through a shopping cart.
	
	- Shopping Cart ID: %2$s

To view the invoice, please click on the URL below:
	
%3$s
		
Best regards,
The %4$s staff';
	
## html message - editable
$html_message = 'Dear %1$s, <br>
<br>
A new invoice has been generated by a seller for a set of items you have purchased from him through a shopping cart. <br>
<br>
<ul>
	<li>Shopping Cart ID: <b>%2$s</b> </li>
</ul>
Please [ <a href="%3$s">click here</a> ] to view the invoice. <br>
<br>
Best regards, <br>
The %4$s staff';
	
	
$invoice_link = SITE_PATH . 'login.php?redirect=' . process_link('invoice_print', array('invoice_type' => 'sc_invoice', 'invoice_id' => $mail_input_id));
	
$text_message = sprintf($text_message, $row_details['username'], $mail_input_id, $invoice_link, $setts['sitename']);
$html_message = sprintf($html_message, $row_details['username'], $mail_input_id, $invoice_link, $setts['sitename']);

send_mail($row_details['email'], 'Cart Invoice Received - Cart ID: ' . $mail_input_id, $text_message, 
	$setts['admin_email'], $html_message, null, $send);
?>
