<div class="globalPartnerMsg">Hi %1$s,


    Thanks for using Bring It Local to support %5$s. We see you just clicked through the banner to %6$s.



    With that one extra click you cast a vote on where you want your money to end up


    If you did end up making a purchase, please expect to see the fundraising results on your member page report within 2 days.
    If this does not show up or you think there was some error please let us know.



    Thanks again for supporting %5$s.



    %7$s



    %8$s
    If you don\'t want to receive similar notification emails any more, please click the link below to unsubscribe.


    <a href ="%4$s">%4$s</a>


    Best regards,


    The Bring It Local staff
</div>